//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewHotelDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Paids = new HashSet<Paid>();
            this.Order_Services = new HashSet<Order_Services>();
            this.Order_Fines = new HashSet<Order_Fines>();
        }
    
        public int id_order { get; set; }
        public int id_client { get; set; }
        public System.DateTime order_date { get; set; }
        public System.DateTime checkin_date { get; set; }
        public System.DateTime checkout_date { get; set; }
        public int id_room { get; set; }
        public int id_employee { get; set; }
        public decimal amount { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paid> Paids { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Services> Order_Services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Fines> Order_Fines { get; set; }
        public virtual Room Room { get; set; }
    }
}
