//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewHotelDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Fines
    {
        public int id_order { get; set; }
        public int id_fine { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<decimal> count { get; set; }
    
        public virtual Fine Fine { get; set; }
        public virtual Order Order { get; set; }
    }
}
