//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewHotelDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Services
    {
        public int id_addserv { get; set; }
        public System.DateTime date { get; set; }
        public decimal count { get; set; }
        public int id_order { get; set; }
    
        public virtual Additional_services Additional_services { get; set; }
        public virtual Order Order { get; set; }
    }
}
